- id: QC_SEC_1
  critical: True (for products requiring authentication)
  name: X.509 Certificate support
  desc: Primary authentication token within the infrastructure is the X.509 certificate
    and its proxy derivatives.
  passfail: Verifier must use X.509 certificates as authentication token. The appliance should
    also support proxy derivatives (e.g. VOMS proxies).
  report: |
    * <span class="label label-success">OK</span> for products able to use X.509 certificates as auth token.
    * <span class="label label-danger">FAIL</span> in any other case.
  revision: Substitutes AUTHN_CRED_1

- id: QC_SEC_2
  critical: True
  name: SHA-2 Certificates Support
  desc: Certificates and proxies generatec with SHA-2 cryptographic hash funtions
    must be supported by the middleware
  passfail: Verification must be performed with SHA-2 certificates for the service and
    for clients.
  testing: See [EGI QC wiki](https://wiki.egi.eu/wiki/EGI_QC_Testing) for more information on 
    SHA-2 certificates.
  report: |
    * <span class="label label-success">OK</span> for products able to use SHA-2 certificates.
    * <span class="label label-danger">FAIL</span> in any other case.
  related: |
    [RT #3078](https://rt.egi.eu/rt/Ticket/Display.html?id=3078)
  revision: Substitutes AUTHN_CRED_2

- id: QC_SEC_3
  critical: False
  name: RFC Proxy support
  desc: All middelware using proxies must accept RFC proxies as credential tokens for authentication
  passfail: Verification must be performed using a RFC proxy. Such proxy can be obtained with the
    `-rfc` option of `voms-proxy-init`.
  testing: See [EGI QC wiki](https://wiki.egi.eu/wiki/EGI_QC_Testing) for more information on 
    RFC proxies.
  report: |
    * <span class="label label-success">OK</span> for products able to use RFC proxies.
    * <span class="label label-warning">WARNING</span> in any other case.
  revision: Substitutes AUTHN_CRED_3

- id: QC_SEC_4
  critical: False
  name: ARGUS Integration
  desc: All services requiring authorization should be able to use an external ARGUS
    service that manages the authorization policies and provides mapping of accounts.
  passfail: Verifier configures an external ARGUS service for the product being verified.
    Test a banning policy and a allowed policy to the resource. Check that the policies are
    enforced.
  testing: See [EGI QC wiki](https://wiki.egi.eu/wiki/EGI_QC_Testing) for using the ARGUS service
    of the verification testbed for this test.
  report: |
    * <span class="label label-success">OK</span> for products that apply correctly the banning 
      and authorized policies of an external ARGUS service.
    * <span class="label label-warning">WARNING</span> for products not supporting ARGUS integration.
  related: |
    [ARGUS Authorization Service](https://twiki.cern.ch/twiki/bin/view/EGEE/AuthorizationFramework)
  revision: Substitutes AUTHZ_ PEP_3

- id: QC_SEC_5
  critical: True
  name: World Writable Files
  desc: World-writable files and directories are dangerous since they allows anyone
    to modify them, several vulnerabilities in recent years have been due to world
    writable files and directories being present when they should not be. No product
    should include or create world writable files in order to prevent new vulnerabilities being
    introduced in the future.
  passfail: Verifier must assure that the product does not include or creates world-writable
    files or directories. If any world-writable files are required for the normal operation
    of the service, these should be documented by the Techonology Provider, a ticket reporting
    the files must be opened. Logs and config files must not be world-writable.
  testing: See [EGI QC wiki](https://wiki.egi.eu/wiki/EGI_QC_Testing) for example test.
  report: |
    * <span class="label label-success">OK</span> for products without world-writabble files
    * <span class="label label-warning">WARNING</span> for products with world-writabble files required for operation and documented.
    * <span class="label label-danger">FAIL</span> for products with world-writtable files that are not documented.
  related: Proposed by the EGI SVG RAT to prevent new vulnerabilities in the future.
  revision: Substitutes GENERIC_SEC_1



- id: QC_SEC_6
  critical: True
  name: Passwords in world readable files
  desc: |
     If the product uses configuration files with any kind of passwords, those files must not be
     world readable.
  passfail: Verifier must check the default permission of configuration files that contain passwords.
    None of them must be readable.
  report: |
    * <span class="label label-success">OK</span> if all files with passwords are not world readable.
    * <span class="label label-danger">FAIL</span> in any other case.
  related: '[SVG Advisory 1414](https://wiki.egi.eu/wiki/SVG:Advisory-SVG-2011-1414)'
  revision: Substitutes GENERIC_SEC_3

